env: gridworld-v0
map: gridworldPlans/plan0.txt
rewards:
  0: -0.001
  3: 1
  4: 1
  5: -1
  6: -1
seed: 5
featExtractor: !!python/name:__main__.MapFromDumpExtractor2 ''
freqSave: 1000
freqTest: 100
nbTest: 10
freqVerbose: 10
fromFile: null
nbTimesteps: 100000
# new hyperparameters
memSize: 50000
learningRate: 0.001
gamma: 0.99
layers: [50]
minEpsilon: 0.02
explorationFraction: 0.1
batchSize: 1