env: CartPole-v1
seed: 5
featExtractor: !!python/name:__main__.NothingToDo ''
freqSave: 1000
freqTest: 100
nbTest: 10
freqVerbose: 10
fromFile: null
nbTimesteps: 100000
# new hyperparameters
memSize: 50000
learningRate: 0.001
gamma: 0.99
layers: [64]
minEpsilon: 0.02
explorationFraction: 0.1
batchSize: 32